ALTER TABLE ANALISTA_CRUDO ADD CONSTRAINT ANALISTA_CRUDO_PK PRIMARY KEY (CRUDO_id, 
    id, 
    HIST_CARGO_fecha_inicio, 
    HIST_CARGO_PERSONAL_INTELIGENCIA_id, 
    HIST_CARGO_ESTACION_id, 
    HIST_CARGO_ESTACION_id1)
;