ALTER TABLE ALT_CRUDO_PIEZA 
    ADD CONSTRAINT ALT_CRUDO_PIEZA_ALT_CRUDO_FK FOREIGN KEY
    ( 
     ALT_CRUDO_id
    ) 
    REFERENCES ALT_CRUDO 
    ( 
     id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    ENFORCED ENABLE QUERY OPTIMIZATION 
;