ALTER TABLE ALT_CRUDO_PIEZA 
    ADD CONSTRAINT ALT_CRUDO_PIEZA_ALT_PIEZA_INTELIGENCIA_FK FOREIGN KEY
    ( 
     ALT_PIEZA_INTELIGENCIA_id
    ) 
    REFERENCES ALT_PIEZA_INTELIGENCIA 
    ( 
     id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    ENFORCED ENABLE QUERY OPTIMIZATION 
;