ALTER TABLE ALT_ANALISTA_CRUDO 
    ADD CONSTRAINT ALT_ANALISTA_CRUDO_ALT_CRUDO_FK FOREIGN KEY
    ( 
     ALT_CRUDO_id
    ) 
    REFERENCES ALT_CRUDO 
    ( 
     id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    ENFORCED ENABLE QUERY OPTIMIZATION 
;