ALTER TABLE ANALISTA_CRUDO 
    ADD CONSTRAINT ANALISTA_CRUDO_CRUDO_FK FOREIGN KEY
    ( 
     CRUDO_id
    ) 
    REFERENCES CRUDO 
    ( 
     id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    ENFORCED ENABLE QUERY OPTIMIZATION 
;