ALTER TABLE AREA_INTERES 
    ADD CONSTRAINT AREA_INTERES_CLIENTE_FK FOREIGN KEY
    ( 
     CLIENTE_id
    ) 
    REFERENCES CLIENTE 
    ( 
     id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    ENFORCED ENABLE QUERY OPTIMIZATION 
;