ALTER TABLE CRUDO_PIEZA 
    ADD CONSTRAINT CRUDO_PIEZA_CRUDO_FK FOREIGN KEY
    ( 
     CRUDO_id
    ) 
    REFERENCES CRUDO 
    ( 
     id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    ENFORCED ENABLE QUERY OPTIMIZATION 
;