ALTER TABLE CRUDO_PIEZA 
    ADD CONSTRAINT CRUDO_PIEZA_PIEZA_INTELIGENCIA_FK FOREIGN KEY
    ( 
     PIEZA_INTELIGENCIA_id
    ) 
    REFERENCES PIEZA_INTELIGENCIA 
    ( 
     id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    ENFORCED ENABLE QUERY OPTIMIZATION 
;