ALTER TABLE EMPLEADO_JEFE 
    ADD CONSTRAINT EMPLEADO_JEFE_EMPLEADO_JEFE_FK FOREIGN KEY
    ( 
     EMPLEADO_JEFE_id
    ) 
    REFERENCES EMPLEADO_JEFE 
    ( 
     id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    ENFORCED ENABLE QUERY OPTIMIZATION 
;