ALTER TABLE ESTACION 
    ADD CONSTRAINT ESTACION_OFICINA_PRINCIPAL_FK FOREIGN KEY
    ( 
     OFICINA_PRINCIPAL_id
    ) 
    REFERENCES OFICINA_PRINCIPAL 
    ( 
     id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    ENFORCED ENABLE QUERY OPTIMIZATION 
;