ALTER TABLE HIST_CARGO 
    ADD CONSTRAINT HIST_CARGO_PERSONAL_INTELIGENCIA_FK FOREIGN KEY
    ( 
     PERSONAL_INTELIGENCIA_id
    ) 
    REFERENCES PERSONAL_INTELIGENCIA 
    ( 
     id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    ENFORCED ENABLE QUERY OPTIMIZATION 
;