ALTER TABLE HIST_CARGO 
    ADD CONSTRAINT HIST_CARGO_ESTACION_FK FOREIGN KEY
    ( 
     ESTACION_id,
     ESTACION_id1
    ) 
    REFERENCES ESTACION 
    ( 
     id,
     OFICINA_PRINCIPAL_id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    ENFORCED ENABLE QUERY OPTIMIZATION 
;