ALTER TABLE INFORMANTE 
    ADD CONSTRAINT INFORMANTE_HIST_CARGO_FK FOREIGN KEY
    ( 
     HIST_CARGO_fecha_inicio,
     HIST_CARGO_PERSONAL_INTELIGENCIA_id,
     HIST_CARGO_ESTACION_id,
     HIST_CARGO_ESTACION_id1
    ) 
    REFERENCES HIST_CARGO 
    ( 
     fecha_inicio,
     PERSONAL_INTELIGENCIA_id,
     ESTACION_id,
     ESTACION_id1
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    ENFORCED ENABLE QUERY OPTIMIZATION 
;