ALTER TABLE INTENTO_NO_AUTORIZADO 
    ADD CONSTRAINT INTENTO_NO_AUTORIZADO_PERSONAL_INTELIGENCIA_FK FOREIGN KEY
    ( 
     PERSONAL_INTELIGENCIA_id
    ) 
    REFERENCES PERSONAL_INTELIGENCIA 
    ( 
     id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    ENFORCED ENABLE QUERY OPTIMIZATION 
;