ALTER TABLE TRANSACCION_PAGO 
    ADD CONSTRAINT TRANSACCION_PAGO_CRUDO_FK FOREIGN KEY
    ( 
     CRUDO_id
    ) 
    REFERENCES CRUDO 
    ( 
     id
    )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    ENFORCED ENABLE QUERY OPTIMIZATION 
;