
-- DIR EJECUTIVO 

SELECT * FROM VER_LUGARES();

CALL CREAR_DIRECTOR_AREA('nombre1','nombre2','apellido1','apellido2',CREAR_TELEFONO(0212,2847213), 5);
SELECT * FROM VER_DIRECTORES_AREA ();


CALL ACTUALIZAR_DIRECTOR_AREA (39,'nombre1_Z','nombre2_Z','apellido1','apellido2',CREAR_TELEFONO(0214,2847213), 1);
SELECT * FROM VER_DIRECTOR_AREA (39);

-- FALTA PROCEDIMIENTOS PARA MODIFICAR EL TELEFONO SIN ACTUALIZAR TODO LO DEMAS 


CALL CREAR_OFICINA_PRINCIPAL('oficina_prueba',false,30,39,null);
SELECT * FROM VER_OFICINAS();

CALL ACTUALIZAR_OFICINA_PRINCIPAL(11,'oficina_prueba_z', false, 30, 39, null);
SELECT * FROM VER_OFICINA(11);


--- CREAR  PERSONAL DE INTELIGENCIA DEDES EMPLEADO_JEFE

CALL CREAR_PERSONAL_INTELIGENCIA (
	'Florentina',
	'Mariluz',
	'Landa',
	'Heredia',
	'1993-03-05',
	189,
	66,
	'verde claro',
	'20/25',
	'top_secret',
	FORMATO_ARCHIVO_A_BYTEA('personal_inteligencia_data/foto.png'),
	FORMATO_ARCHIVO_A_BYTEA('personal_inteligencia_data/huella_digital.png'),
	FORMATO_ARCHIVO_A_BYTEA('personal_inteligencia_data/huella_retina.png'),
	CREAR_TELEFONO(58,4145866510) ,CREAR_LICENCIA('75518194','Argentina'),
	CREAR_ARRAY_IDIOMAS('inglés','árabe','portugués','francés',NULL,NULL),
	CREAR_FAMILIAR('Araceli',null,'Alcantara','Candelaria','1960-06-01','tío',58,4145335249 ),
	CREAR_FAMILIAR('Calixtrato','Vicente','Quintanilla','Estrada','1960-06-01','hermano',58,4142583859),
	CREAR_IDENTIFICACION('31656053','Irlanda'),
	CREAR_NIVEL_EDUCATIVO('Economía','Máster','Finanzas'),
	10
	);


CALL ACTUALIZAR_PERSONAL_INTELIGENCIA (
	 16,
	 21,
	 'GABRIEL',
	 'ALBERTO',
	 'ULACIO',
	 'MANRIQUE',
	 '1995-03-09',
	 165,
	 70, 
	 'negro', 
	 '20/20',
	 'no_clasificado',
	 FORMATO_ARCHIVO_A_BYTEA('personal_inteligencia_data/foto.png'),
	 FORMATO_ARCHIVO_A_BYTEA('personal_inteligencia_data/huella_retina.png'),   FORMATO_ARCHIVO_A_BYTEA('personal_inteligencia_data/huella_digital.png'),
     CREAR_TELEFONO(0212,2847268),
     CREAR_LICENCIA('021390213','Argentina'),
     CREAR_ARRAY_IDIOMAS('español','italiano','chino','portugués',null,null),
     CREAR_FAMILIAR ('Gabriel','alberto,','manrique','ulacio','1960-06-01','tio',0414,0176620),
     CREAR_FAMILIAR ('familiarn2','familiarn2,','familiara2','familiara2','1980-07-01','primo',0416,7876620),
     CREAR_IDENTIFICACION('0213120431','Australia'),
     CREAR_NIVEL_EDUCATIVO('Economía', 'Master', 'Finanzas'),
 	20
 );


--- FUNCION PARA TODO EL PERSONAL QUE NO TIENE UN CARGO ASIGNADO --
SELECT * FROM VER_TODOS_PERSONAL_INTELIGENCIA_SIN_CARGO()

--- ORICEDIMIENTO ELIMINAR PERSONAL DE INTELIGENCIA QUE NO TENGA CARGO ---
--- PARAMETRO: ID DE JEFE DE ESTACION E ID DE PERSONAL INTELIGENCIA ---
--- ID DE EMPLEADO JEFE DESDE [11,37]

CALL ELIMINAR_PERSONAL_INTELIGENCIA(11,1)


--- ASISNGNACION DE HISTORICO CARGO A PERSONAL ---
--- PARAMETROS: ID JEFE_ESTACION, ID PERSONAL, ID ESTACION, CARGO ('agente','analista') ---

CALL ASIGNAR_TRANSFERIR_ESTACION_EMPLEADO (20,109,10,'analista')


--- FUNCTION PARA VER EL PERSONAL DE INTELIGENCIA QUE ESTA ENCARGADO EL JEFE ---
--- PARAMETROS: ID JEFE ---
SELECT * FROM VER_TODOS_PERSONAL_INTELIGENCIA_CON_CARGO(11)


--- FUNCION PARA VER EL HISTORICO CARGO DE LOS EMPLEADOS POR JEFE DE ESTACION ---
SELECT * FROM VER_HISTORICO_CARGO_PERSONAL_INTELIGENCIA (11,1)

--- ASIGNACION DE TEMA AL ANALISTA ---
--- PARAMETROS ID:JEFE_ESTACION, ID TEMA, ID PERSONAL INTELIGENCIA CON EL ANALISTA ---
CALL ASIGNAR_TEMA_ANALISTA(16,2,21);


--- FUNCION PARA CERRAR EL HISTORICO CARGO DE UN PERSONAL DE INTELIGENCIA ---
--- PARAMETROS: ID DE JEFE DE ESTACION, ID DEL PERSONAL INTELIGENCIA
CALL CERRAR_HIST_CARGO (11,1)



