
-- DIR EJECUTIVO 

SELECT * FROM VER_LUGARES();

CALL CREAR_DIRECTOR_AREA('nombre1','nombre2','apellido1','apellido2',CREAR_TELEFONO(0212,2847213), 5);
SELECT * FROM VER_DIRECTORES_AREA ();


CALL ACTUALIZAR_DIRECTOR_AREA (39,'nombre1_Z','nombre2_Z','apellido1','apellido2',CREAR_TELEFONO(0214,2847213), 1);
SELECT * FROM VER_DIRECTOR_AREA (39);

-- FALTA PROCEDIMIENTOS PARA MODIFICAR EL TELEFONO SIN ACTUALIZAR TODO LO DEMAS 


CALL CREAR_OFICINA_PRINCIPAL('oficina_prueba',false,30,39,null);
SELECT * FROM VER_OFICINAS();

CALL ACTUALIZAR_OFICINA_PRINCIPAL(11,'oficina_prueba_z', false, 30, 39, null);
SELECT * FROM VER_OFICINA(11);










