select pg_terminate_backend(pid) from pg_stat_activity where datname='aii'
-----------DIRECTOR EJECUTIVO -------

-------------------- ROL DIRECTOR EJECUTIVO -------------- ID: 1

-----CREACION DE DIRECTOR DE AREA ------
-----PARAMETROS: NOMBRE COMPLETOS, FUNCION CREAR_TELEFONO (CODIGO,NUMERO), FK_EMPLEADO_JEFE
-- CALL CREAR_DIRECTOR_AREA('nombre1','nombre2','apellido1','apellido2',CREAR_TELEFONO(0212,2847213), 12);
CALL CREAR_DIRECTOR_AREA('nombre1','nombre2','apellido1','apellido2',CREAR_TELEFONO(0212,2847213), 1);


----MOUESTRA LOS DIRECTORES AREA ----
SELECT * FROM VER_DIRECTORES_AREA ();

-----PARAMETROS: ID_DE_DIRECTOR A ACTUALIZAR, NOMBRE COMPLETOS, FUNCION CREAR_TELEFONO (CODIGO,NUMERO), FK_EMPLEADO_JEFE
CALL ACTUALIZAR_DIRECTOR_AREA (39,'nombre1_Z','nombre2_Z','apellido1','apellido2',CREAR_TELEFONO(0214,2847213), 1);
SELECT * FROM VER_DIRECTOR_AREA (39);

----- PARAMETROS: ID DEL DIRECTOR DE AREA A ELIMINAS
CALL ELIMINAR_DIRECTOR_AREA(43)


----- SOLO DIRECTOR EJECUTIVO  ------
SELECT * FROM VER_LUGARES();

----- CREACION DE OFICINA PRINCIPAL----
--CALL crear_oficina_principal(:nombre_va, :sede_va, :id_ciudad, :id_director_area, :id_director_ejecutivo) 
CALL CREAR_OFICINA_PRINCIPAL('oficina_prueba',false,19,40,null);
SELECT * FROM VER_OFICINAS();

CALL ACTUALIZAR_OFICINA_PRINCIPAL(11,'oficina_prueba_z', false, 30, 39, null);
SELECT * FROM VER_OFICINA(11);


------------------	DIRECTOR_AREA ID=3  AMSTERDAM ----------------------- cambio de rol


-- PARAMETROS: ID_EMPLEADO_ACCESO
SELECT VER_JEFES_E (3);

-- PARAMETROS: ID_EMPLEADO_ACCESO_AREA, ID JEFE_ESTACION
--call ver_jefe_e(:id_empleado_acceso, :id_jefe) 
--SELECT VER_JEFE_E (3,12);
SELECT VER_JEFE_E (3,14);


-- PARAMETROS: ID_EMPLEADO_ACCESO, ESTACIONES A CARGO DEL JEFE
--SELECT * FROM VER_ESTACIONES(2);
SELECT * FROM VER_ESTACIONES(3);


-- PARAMETROS: ID_EMPLEADO_ACCESO, ID ESTACION, SI ES CARGO DE LA ESTACION
--SELECT * FROM VER_ESTACION(3,12);
SELECT * FROM VER_ESTACION(3,4);




-- PARAMETROS: ID_EMPLEADO_ACCESO, ID ESTACION, PRESUPUESTO DE LA ESTACION POR JEFE
SELECT * from VER_PRESUPUESTO_ESTACION(3,4);

--CALL asignacion_presupuesto(:id_empleado_acceso, :estacion_va, :presupuesto_va) 
CALL asignacion_presupuesto(3, 4, 200 ) 


-- MUESTRA TODOS LOS CLIENTES
SELECT VER_CLIENTES();

-- PARAMETROS: ID_CLIENTE, MUESTRA LA INFORMACION DE UN CLIENTE
SELECT VER_CLIENTE(8);



-- PARAMETROS: ID_EMPLEADO_JEFE, NOMBRES, TELEFONO, DIRECTOR DE AREA CREAR AL JEFE DE ESTACION
CALL CREAR_JEFE_ESTACION(3,'nombre1','nombre2','apellido1','apellido2',CREAR_TELEFONO(0212,2847213));

-- PARAMETROS: ID_EMPLEADO_JEFE, NOMBRES, TELEFONO, DIRECTOR DE AREA ACTUALIZA AL JEFE DE ESTACION (SI TIENE ACCESO)
CALL actualizar_jefe_estacion (1,11,'nombre1','nombre2','apellido1','apellido2',CREAR_TELEFONO(0212,2847213), 5);

-- PARAMETROS: ID_EMPLEADO_JEFE, ID_JEFE_ESTACION, ELIMINA AL JEFE DE ESTACION (SI TIENE ACCESO)
CALL ELIMINAR_JEFE_ESTACION(2,44);

-- PARAMETROS: ID_EMPLEADO_JEFE, NOMBRE_ESTACION, ID_CIUDAD, JEFE_ESTACION, CREAR ESTACION
-- call crear_estacion(:id_empleado_acceso, :nombre_va, :id_ciudad, :id_jefe_estacion) 
CALL CREAR_ESTACION(3, 'prueba',20, 41);

-- PARAMETROS: ID_EMPLEADO_JEFE, ID_ESTACION, ELIMINA LA ESTACION EL DIRECTOR DE AREA (SI TIENE ACCESO)
CALL ELIMINAR_ESTACION(3,15);

-- PARAMETROS: ID_EMPLEADO_JEFE, ID_ESTACION, ELIMINA LA ESTACION EL DIRECTOR DE AREA (SI TIENE ACCESO)
CALL ACTUALIZAR_ESTACION (13,'nombre1', 21, 39 );





-- PARAMETROS: NOMBRE DE LA EMPRESA, PAGINA WEB, CONFIDENTE (BOOL), TELEFONO, ID_LUGAR_PAIS
CALL CREAR_CLIENTE('nombre_empresa','pagina_web', true,CREAR_TELEFONO(0212,2847213), CREAR_CONTACTO('gabriel','alberto','manrique','ulacio','calle_tal',0414,0176620), 5);

-- PARAMETROS: ID_CLIENTE (VALIDA LAS RELACIONES DEL CLITENE, SI TIENE UNA COMPRA)
CALL ELIMINAR_CLIENTE(11);

-- PARAMETROS: ID_DEL CLIENTE, NOMBRE DE LA EMPRESA, PAGINA WEB, CONFIDENTE (BOOL), TELEFONO, ID_LUGAR_PAIS
CALL ACTUALIZAR_CLIENTE(2,'nombre_empresa','pagina_web',false,CREAR_TELEFONO(0212,2847213),null, 5);

-- PARAMETROS: ID_DEL TEMA A ASIGNAR Y EL CLIENTE, AGREGA TEMA EN LA TABLA area_interes
CALL ASIGNAR_TEMA_CLIENTE (2, 10);


------------- JEFE DE ESTACION ID 14 estacion amsterdam------------

-------------- CREAR  PERSONAL DE INTELIGENCIA DESDE EMPLEADO_JEFE -------------- cambio de rol

CALL CREAR_PERSONAL_INTELIGENCIA (
	'Florentina',
	'Mariluz',
	'Landa',
	'Heredia',
	'1993-03-05',
	189,
	66,
	'verde claro',
	'20/25',
	'top_secret',
	FORMATO_ARCHIVO_A_BYTEA('personal_inteligencia_data/foto.png'),
	FORMATO_ARCHIVO_A_BYTEA('personal_inteligencia_data/huella_digital.png'),
	FORMATO_ARCHIVO_A_BYTEA('personal_inteligencia_data/huella_retina.png'),
	CREAR_TELEFONO(58,4145866510) ,CREAR_LICENCIA('75518194','Argentina'),
	CREAR_ARRAY_IDIOMAS('ingles','arabe','portugues','frances',NULL,NULL),
	CREAR_FAMILIAR('Araceli',null,'Alcantara','Candelaria','1960-06-01','t�o',58,4145335249 ),
	CREAR_FAMILIAR('Calixtrato','Vicente','Quintanilla','Estrada','1960-06-01','hermano',58,4142583859),
	CREAR_IDENTIFICACION('31656053','Irlanda'),
	CREAR_NIVEL_EDUCATIVO('Economia','Master','Finanzas'),
	10
	);

--- CREAR  ACTUALIZAR DE INTELIGENCIA DESDE EMPLEADO_JEFE

CALL ACTUALIZAR_PERSONAL_INTELIGENCIA (
	 16,
	 21,
	 'GABRIEL',
	 'ALBERTO',
	 'ULACIO',
	 'MANRIQUE',
	 '1995-03-09',
	 165,
	 70, 
	 'negro', 
	 '20/20',
	 'no_clasificado',
	 FORMATO_ARCHIVO_A_BYTEA('personal_inteligencia_data/foto.png'),
	 FORMATO_ARCHIVO_A_BYTEA('personal_inteligencia_data/huella_retina.png'),   FORMATO_ARCHIVO_A_BYTEA('personal_inteligencia_data/huella_digital.png'),
     CREAR_TELEFONO(0212,2847268),
     CREAR_LICENCIA('021390213','Argentina'),
     CREAR_ARRAY_IDIOMAS('espa�ol','italiano','chino','portugu�s',null,null),
     CREAR_FAMILIAR ('Gabriel','alberto,','manrique','ulacio','1960-06-01','tio',0414,0176620),
     CREAR_FAMILIAR ('familiarn2','familiarn2,','familiara2','familiara2','1980-07-01','primo',0416,7876620),
     CREAR_IDENTIFICACION('0213120431','Australia'),
     CREAR_NIVEL_EDUCATIVO('Econom�a', 'Master', 'Finanzas'),
 	20
 );


--------------JEFE ESTACION -------------

--- FUNCION PARA TODO EL PERSONAL QUE NO TIENE UN CARGO ASIGNADO --
SELECT * FROM VER_TODOS_PERSONAL_INTELIGENCIA_SIN_CARGO();
select * from hist_cargo; 

--- ORICEDIMIENTO ELIMINAR PERSONAL DE INTELIGENCIA QUE NO TENGA CARGO ---
--- PARAMETRO: ID DE JEFE DE ESTACION E ID DE PERSONAL INTELIGENCIA ---
--- ID DE EMPLEADO JEFE DESDE [11,37]

CALL ELIMINAR_PERSONAL_INTELIGENCIA(11,1)


--- ASISNGNACION DE HISTORICO CARGO A PERSONAL ---
--- PARAMETROS: ID JEFE_ESTACION, ID PERSONAL, ID ESTACION, CARGO ('agente','analista') ---
--call asignar_transferir_estacion_empleado(:id_empleado_acceso, :id_personal_inteligencia, :id_estacion, :cargo_va) 
CALL ASIGNAR_TRANSFERIR_ESTACION_EMPLEADO (14,103,4,'analista');


--- FUNCTION PARA VER EL PERSONAL DE INTELIGENCIA QUE ESTA ENCARGADO EL JEFE ---
--- PARAMETROS: ID JEFE ---
SELECT * FROM VER_TODOS_PERSONAL_INTELIGENCIA_CON_CARGO(14)


--- FUNCION PARA VER EL HISTORICO CARGO DE LOS EMPLEADOS POR JEFE DE ESTACION ---
SELECT * FROM VER_HISTORICO_CARGO_PERSONAL_INTELIGENCIA (11,1)

--- ASIGNACION DE TEMA AL ANALISTA ---
--- PARAMETROS ID:JEFE_ESTACION, ID TEMA, ID PERSONAL INTELIGENCIA CON EL ANALISTA ---
CALL ASIGNAR_TEMA_ANALISTA(16,2,21);


--- FUNCION PARA CERRAR EL HISTORICO CARGO DE UN PERSONAL DE INTELIGENCIA ---
--- PARAMETROS: ID DE JEFE DE ESTACION, ID DEL PERSONAL INTELIGENCIA
--CALL CERRAR_HIST_CARGO (14,103);


CALL DESPIDO_RENUNCIA_PERSONAL_INTELIGENCIA(14,103);





