

-------------------- ROL DIRECTOR EJECUTIVO -------------- ID: 1
----- SOLO DIRECTOR EJECUTIVO  ------
SELECT * FROM VER_LUGARES();

-----CREACION DE DIRECTOR DE AREA ------
-----PARAMETROS: NOMBRE COMPLETOS, FUNCION CREAR_TELEFONO (CODIGO,NUMERO), FK_EMPLEADO_JEFE
CALL CREAR_DIRECTOR_AREA('nombre1','nombre2','apellido1','apellido2',CREAR_TELEFONO(0212,2847213), 12);

----MOUESTRA LOS DIRECTORES AREA ----
SELECT * FROM VER_DIRECTORES_AREA ();

-----PARAMETROS: ID_DE_DIRECTOR A ACTUALIZAR, NOMBRE COMPLETOS, FUNCION CREAR_TELEFONO (CODIGO,NUMERO), FK_EMPLEADO_JEFE
CALL ACTUALIZAR_DIRECTOR_AREA (39,'nombre1_Z','nombre2_Z','apellido1','apellido2',CREAR_TELEFONO(0214,2847213), 1);
SELECT * FROM VER_DIRECTOR_AREA (39);
