-- INSERT INTO ADQUISICION (fecha_hora_venta, precio_vendido, fk_cliente, fk_pieza_inteligencia) VALUES

-- clientes exclusivos: 1, 2, 5, 6, 9, 10, 13, 14, 17, 18
-- Una pieza de inteligencia de venta exclusiva tiene al menos el 45% de recargo de su precio base.

--     -- ('2035-12-02 17:00:00', 1544, 1, 1),
--     -- ('2034-12-04 07:00:00', 1870, 1, 2),
--     -- ('2034-12-05 02:00:00', 1820, 1, 3),
--     ('2036-09-06 03:00:00', 1700, 2, 4),
--     -- ('2035-08-16 04:00:00', 1850, 2, 5),
--     ('2036-02-12 17:00:00', 1500, 5, 10),
-- --    ('2034-03-28 07:00:00', 1880, 6, 11),
--     -- ('2035-09-02 04:00:00', 1966, 10, 14),
--     -- ('2035-12-22 17:00:00', 2030, 9, 16),
--     -- ('2034-12-05 02:00:00', 1987, 10, 12), 
    
    
    
    
--CALL ELIMINACION_REGISTROS_VENTA_EXCLUSIVA( 1 );
 



CALL ELIMINACION_REGISTROS_VENTA_EXCLUSIVA (11);
CALL ELIMINACION_REGISTROS_VENTA_EXCLUSIVA (2);
CALL ELIMINACION_REGISTROS_VENTA_EXCLUSIVA (3);
CALL ELIMINACION_REGISTROS_VENTA_EXCLUSIVA (12);
CALL ELIMINACION_REGISTROS_VENTA_EXCLUSIVA (5);
CALL ELIMINACION_REGISTROS_VENTA_EXCLUSIVA (14);
CALL ELIMINACION_REGISTROS_VENTA_EXCLUSIVA (1);
CALL ELIMINACION_REGISTROS_VENTA_EXCLUSIVA (16);
CALL ELIMINACION_REGISTROS_VENTA_EXCLUSIVA (10);
CALL ELIMINACION_REGISTROS_VENTA_EXCLUSIVA (4);

-- CALL REGISTRO_VENTA (11,6,1880);
-- CALL REGISTRO_VENTA (2,1,1870);
-- CALL REGISTRO_VENTA (3,1,1820);
-- CALL REGISTRO_VENTA (12,10,1987);
-- CALL REGISTRO_VENTA (5,2,1850);
-- CALL REGISTRO_VENTA (14,10,1966);
-- CALL REGISTRO_VENTA (1,1,1544);
-- CALL REGISTRO_VENTA (16,9,2030);
-- CALL REGISTRO_VENTA (10,5,1500);
-- CALL REGISTRO_VENTA (4,2,1700);

-- SELECT fk_crudo FROM CRUDO_PIEZA_ALT;

-- select * from TRANSACCION_PAGO_ALT order by fk_informante;
-- select * from INFORMANTE_ALT;
-- select id,fuente,fk_personal_inteligencia_agente,fk_clas_tema,fk_informante from CRUDO_ALT ORDER BY fk_informante

-- select * from CRUDO_ALT  order by 





CREATE OR REPLACE PROCEDURE NUMERO_REGISTROS ()
LANGUAGE plpgsql
AS $$
DECLARE

    LUGAR_n integer;
    CLIENTE_n integer;
    EMPLEADO_JEFE_n integer;
    OFICINA_PRINCIPAL_n integer;
    ESTACION_n integer;
    CUENTA_n integer;
    PERSONAL_INTELIGENCIA_n integer;
    INTENTO_NO_AUTORIZADO_n integer;
    CLAS_TEMA_n integer;
    AREA_INTERES_n integer;
    TEMAS_ESP_n integer;
    HIST_CARGO_n integer;
    INFORMANTE_n integer;
    TRANSACCION_PAGO_n integer;
    CRUDO_n integer;
    ANALISTA_CRUDO_n integer;
    PIEZA_INTELIGENCIA_n integer;
    CRUDO_PIEZA_n integer;
    ADQUISICION_n integer;

    HIST_CARGO_ALT_n integer;
    INFORMANTE_ALT_n integer;
    TRANSACCION_PAGO_ALT_n integer;
    CRUDO_ALT_n integer;
    ANALISTA_CRUDO_ALT_n integer;
    PIEZA_INTELIGENCIA_ALT_n integer;
    CRUDO_PIEZA_ALT_n integer;
    ADQUISICION_ALT_n integer;

    TOTAL integer;

BEGIN

    SELECT count(*) INTO LUGAR_n FROM LUGAR;
    SELECT count(*) INTO CLIENTE_n FROM CLIENTE;
    SELECT count(*) INTO EMPLEADO_JEFE_n FROM EMPLEADO_JEFE;
    SELECT count(*) INTO OFICINA_PRINCIPAL_n FROM OFICINA_PRINCIPAL;
    SELECT count(*) INTO ESTACION_n FROM ESTACION;
    SELECT count(*) INTO CUENTA_n FROM CUENTA;
    SELECT count(*) INTO PERSONAL_INTELIGENCIA_n FROM PERSONAL_INTELIGENCIA;
    SELECT count(*) INTO INTENTO_NO_AUTORIZADO_n FROM INTENTO_NO_AUTORIZADO;
    SELECT count(*) INTO CLAS_TEMA_n FROM CLAS_TEMA;
    SELECT count(*) INTO AREA_INTERES_n FROM AREA_INTERES;
    SELECT count(*) INTO TEMAS_ESP_n FROM TEMAS_ESP;
    SELECT count(*) INTO HIST_CARGO_n FROM HIST_CARGO;
    SELECT count(*) INTO INFORMANTE_n FROM INFORMANTE;
    SELECT count(*) INTO TRANSACCION_PAGO_n FROM TRANSACCION_PAGO;
    SELECT count(*) INTO CRUDO_n FROM CRUDO;
    SELECT count(*) INTO ANALISTA_CRUDO_n FROM ANALISTA_CRUDO;
    SELECT count(*) INTO PIEZA_INTELIGENCIA_n FROM PIEZA_INTELIGENCIA;
    SELECT count(*) INTO CRUDO_PIEZA_n FROM CRUDO_PIEZA;
    SELECT count(*) INTO ADQUISICION_n FROM ADQUISICION;

    SELECT count(*) INTO HIST_CARGO_ALT_n FROM HIST_CARGO_ALT;
    SELECT count(*) INTO INFORMANTE_ALT_n FROM INFORMANTE_ALT;
    SELECT count(*) INTO TRANSACCION_PAGO_ALT_n FROM TRANSACCION_PAGO_ALT;
    SELECT count(*) INTO CRUDO_ALT_n FROM CRUDO_ALT;
    SELECT count(*) INTO ANALISTA_CRUDO_ALT_n FROM ANALISTA_CRUDO_ALT;
    SELECT count(*) INTO PIEZA_INTELIGENCIA_ALT_n FROM PIEZA_INTELIGENCIA_ALT;
    SELECT count(*) INTO CRUDO_PIEZA_ALT_n FROM CRUDO_PIEZA_ALT;
    SELECT count(*) INTO ADQUISICION_ALT_n FROM ADQUISICION_ALT;

    TOTAL :=  LUGAR_n + CLIENTE_n + EMPLEADO_JEFE_n + OFICINA_PRINCIPAL_n + ESTACION_n + CUENTA_n + PERSONAL_INTELIGENCIA_n + INTENTO_NO_AUTORIZADO_n + CLAS_TEMA_n + AREA_INTERES_n + TEMAS_ESP_n + HIST_CARGO_n + INFORMANTE_n + TRANSACCION_PAGO_n + CRUDO_n + ANALISTA_CRUDO_n + PIEZA_INTELIGENCIA_n + CRUDO_PIEZA_n + ADQUISICION_n + HIST_CARGO_ALT_n + INFORMANTE_ALT_n + TRANSACCION_PAGO_ALT_n + CRUDO_ALT_n + ANALISTA_CRUDO_ALT_n + PIEZA_INTELIGENCIA_ALT_n + CRUDO_PIEZA_ALT_n + ADQUISICION_ALT_n;


    RAISE INFO 'CLIENTE_n: %', CLIENTE_n;
    RAISE INFO 'LUGAR_n: %', LUGAR_n;
    RAISE INFO 'EMPLEADO_JEFE_n: %', EMPLEADO_JEFE_n;
    RAISE INFO 'OFICINA_PRINCIPAL_n: %', OFICINA_PRINCIPAL_n;
    RAISE INFO 'ESTACION_n: %', ESTACION_n;
    RAISE INFO 'CUENTA_n: %', CUENTA_n;
    RAISE INFO 'PERSONAL_INTELIGENCIA_n: %', PERSONAL_INTELIGENCIA_n;
    RAISE INFO 'INTENTO_NO_AUTORIZADO_n: %', INTENTO_NO_AUTORIZADO_n;
    RAISE INFO 'CLAS_TEMA_n: %', CLAS_TEMA_n;
    RAISE INFO 'AREA_INTERES_n: %', AREA_INTERES_n;
    RAISE INFO 'TEMAS_ESP_n: %', TEMAS_ESP_n;
    RAISE INFO 'HIST_CARGO_n: %', HIST_CARGO_n;
    RAISE INFO 'INFORMANTE_n: %', INFORMANTE_n;
    RAISE INFO 'TRANSACCION_PAGO_n: %', TRANSACCION_PAGO_n;
    RAISE INFO 'CRUDO_n: %', CRUDO_n;
    RAISE INFO 'ANALISTA_CRUDO_n: %', ANALISTA_CRUDO_n;
    RAISE INFO 'PIEZA_INTELIGENCIA_n: %', PIEZA_INTELIGENCIA_n;
    RAISE INFO 'CRUDO_PIEZA_n: %', CRUDO_PIEZA_n;
    RAISE INFO 'ADQUISICION_n: %', ADQUISICION_n;
    RAISE INFO 'HIST_CARGO_ALT_n: %', HIST_CARGO_ALT_n;
    RAISE INFO 'INFORMANTE_ALT_n: %', INFORMANTE_ALT_n;
    RAISE INFO 'TRANSACCION_PAGO_ALT_n: %', TRANSACCION_PAGO_ALT_n;
    RAISE INFO 'CRUDO_ALT_n: %', CRUDO_ALT_n;
    RAISE INFO 'ANALISTA_CRUDO_ALT_n: %', ANALISTA_CRUDO_ALT_n;
    RAISE INFO 'PIEZA_INTELIGENCIA_ALT_n: %', PIEZA_INTELIGENCIA_ALT_n;
    RAISE INFO 'CRUDO_PIEZA_ALT_n: %', CRUDO_PIEZA_ALT_n;
    RAISE INFO 'ADQUISICION_ALT_n: %', ADQUISICION_ALT_n;
    RAISE INFO ' TOTAL % ', TOTAL;

END $$;



-- SIN VENTAS
CALL NUMERO_REGISTROS();
--
--CLIENTE_n: 20
--LUGAR_n: 38
--EMPLEADO_JEFE_n: 38
--OFICINA_PRINCIPAL_n: 10
--ESTACION_n: 27
--CUENTA_n: 81
--PERSONAL_INTELIGENCIA_n: 102
--INTENTO_NO_AUTORIZADO_n: 10
--CLAS_TEMA_n: 9
--AREA_INTERES_n: 20
--TEMAS_ESP_n: 0
--HIST_CARGO_n: 204
--INFORMANTE_n: 21
--TRANSACCION_PAGO_n: 12
--CRUDO_n: 29
--ANALISTA_CRUDO_n: 64
--PIEZA_INTELIGENCIA_n: 27
--CRUDO_PIEZA_n: 71
--ADQUISICION_n: 30
--HIST_CARGO_ALT_n: 0
--INFORMANTE_ALT_n: 0
--TRANSACCION_PAGO_ALT_n: 0
--CRUDO_ALT_n: 0
--ANALISTA_CRUDO_ALT_n: 0
--PIEZA_INTELIGENCIA_ALT_n: 0
--CRUDO_PIEZA_ALT_n: 0
--ADQUISICION_ALT_n: 0
-- TOTAL 813 



-- CON VENTAS
--CALL NUMERO_REGISTROS();
--CLIENTE_n: 20
--LUGAR_n: 38
--EMPLEADO_JEFE_n: 38
--OFICINA_PRINCIPAL_n: 10
--ESTACION_n: 27
--CUENTA_n: 81
--PERSONAL_INTELIGENCIA_n: 102
--INTENTO_NO_AUTORIZADO_n: 10
--CLAS_TEMA_n: 9
--AREA_INTERES_n: 20
--TEMAS_ESP_n: 0
--HIST_CARGO_n: 204
--INFORMANTE_n: 21
--TRANSACCION_PAGO_n: 0
--CRUDO_n: 6
--ANALISTA_CRUDO_n: 13
--PIEZA_INTELIGENCIA_n: 17
--CRUDO_PIEZA_n: 48
--ADQUISICION_n: 20
--HIST_CARGO_ALT_n: 0
--INFORMANTE_ALT_n: 0
--TRANSACCION_PAGO_ALT_n: 12
--CRUDO_ALT_n: 23
--ANALISTA_CRUDO_ALT_n: 51
--PIEZA_INTELIGENCIA_ALT_n: 10
--CRUDO_PIEZA_ALT_n: 23
--ADQUISICION_ALT_n: 20
--
--TOTAL 823 

